name: learn_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ">=2.17.6 <3.0.0"

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: 4.6.5
  firebase_core: 2.1.0
  change_app_package_name: ^1.1.0
  firebase_auth: 4.0.2
  google_sign_in: 5.4.2
  font_awesome_flutter: ^10.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

